version: "3.9" # optional since v1.27.0
services:
  web:
    build: .
    ports:
      - "8888:8080"
    volumes:
      - .:/app
  build:
    build: .
    command: npm run watch
    volumes:
      - .:/app
  couchdb:
    image: couchdb:3
    ports:
      - "5984:5984"
    environment:
      COUCHDB_USER: username
      COUCHDB_PASSWORD: password
